//
// Bitmap font C header file generated by bmfont2c.py 
// 

#ifndef FONTLIBRARY_H_
#define FONTLIBRARY_H_

#include <stdint.h>

typedef struct
{
    uint8_t GlyphCount;
    uint8_t FirstAsciiCode;
    uint8_t GlyphBytesWidth;
    uint8_t GlyphHeight;
    uint8_t FixedWidth;
    uint8_t const *GlyphWidth;
    uint8_t const *GlyphBitmaps;
} fontStyle_t;

static uint8_t const Emulogic_Bitmaps[940] = 
{
    // ASCII: 32, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x00,  // --------
    0x00,  // --------
    0x00,  // --------
    0x00,  // --------
    0x00,  // --------
    0x00,  // --------
    0x00,  // --------
    0x00,  // --------

    // ASCII: 33, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x38,  // --OOO---
    0x38,  // --OOO---
    0x38,  // --OOO---
    0x30,  // --OO----
    0x30,  // --OO----
    0x00,  // --------
    0x30,  // --OO----
    0x00,  // --------

    // ASCII: 34, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x6c,  // -OO-OO--
    0x6c,  // -OO-OO--
    0x48,  // -O--O---
    0x00,  // --------
    0x00,  // --------
    0x00,  // --------
    0x00,  // --------
    0x00,  // --------

    // ASCII: 35, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x6c,  // -OO-OO--
    0x6c,  // -OO-OO--
    0xfe,  // OOOOOOO-
    0x6c,  // -OO-OO--
    0xfe,  // OOOOOOO-
    0x6c,  // -OO-OO--
    0x6c,  // -OO-OO--
    0x00,  // --------

    // ASCII: 36, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x10,  // ---O----
    0x7c,  // -OOOOO--
    0xd0,  // OO-O----
    0x7c,  // -OOOOO--
    0x16,  // ---O-OO-
    0x7c,  // -OOOOO--
    0x10,  // ---O----
    0x00,  // --------

    // ASCII: 37, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x42,  // -O----O-
    0xa4,  // O-O--O--
    0x48,  // -O--O---
    0x10,  // ---O----
    0x24,  // --O--O--
    0x4a,  // -O--O-O-
    0x84,  // O----O--
    0x00,  // --------

    // ASCII: 38, char width: 9
    0x00,  // --------
    0x00,  // --------
    0x38,  // --OOO---
    0x44,  // -O---O--
    0x74,  // -OOO-O--
    0x78,  // -OOOO---
    0x9d,  // O--OOO-O
    0x86,  // O----OO-
    0x7d,  // -OOOOO-O
    0x00,  // --------

    // ASCII: 39, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x60,  // -OO-----
    0x60,  // -OO-----
    0x20,  // --O-----
    0x40,  // -O------
    0x00,  // --------
    0x00,  // --------
    0x00,  // --------
    0x00,  // --------

    // ASCII: 40, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x18,  // ---OO---
    0x30,  // --OO----
    0x60,  // -OO-----
    0x60,  // -OO-----
    0x60,  // -OO-----
    0x30,  // --OO----
    0x18,  // ---OO---
    0x00,  // --------

    // ASCII: 41, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x30,  // --OO----
    0x18,  // ---OO---
    0x0c,  // ----OO--
    0x0c,  // ----OO--
    0x0c,  // ----OO--
    0x18,  // ---OO---
    0x30,  // --OO----
    0x00,  // --------

    // ASCII: 42, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x00,  // --------
    0x44,  // -O---O--
    0x28,  // --O-O---
    0x10,  // ---O----
    0x28,  // --O-O---
    0x44,  // -O---O--
    0x00,  // --------
    0x00,  // --------

    // ASCII: 43, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x00,  // --------
    0x10,  // ---O----
    0x10,  // ---O----
    0x7c,  // -OOOOO--
    0x10,  // ---O----
    0x10,  // ---O----
    0x00,  // --------
    0x00,  // --------

    // ASCII: 44, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x00,  // --------
    0x00,  // --------
    0x00,  // --------
    0x00,  // --------
    0x30,  // --OO----
    0x30,  // --OO----
    0x60,  // -OO-----
    0x00,  // --------

    // ASCII: 45, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x00,  // --------
    0x00,  // --------
    0x00,  // --------
    0x7c,  // -OOOOO--
    0x00,  // --------
    0x00,  // --------
    0x00,  // --------
    0x00,  // --------

    // ASCII: 46, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x00,  // --------
    0x00,  // --------
    0x00,  // --------
    0x00,  // --------
    0x00,  // --------
    0x30,  // --OO----
    0x30,  // --OO----
    0x00,  // --------

    // ASCII: 47, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x02,  // ------O-
    0x04,  // -----O--
    0x08,  // ----O---
    0x10,  // ---O----
    0x20,  // --O-----
    0x40,  // -O------
    0x80,  // O-------
    0x00,  // --------

    // ASCII: 48, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x38,  // --OOO---
    0x4c,  // -O--OO--
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0x64,  // -OO--O--
    0x38,  // --OOO---
    0x00,  // --------

    // ASCII: 49, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x18,  // ---OO---
    0x38,  // --OOO---
    0x18,  // ---OO---
    0x18,  // ---OO---
    0x18,  // ---OO---
    0x18,  // ---OO---
    0x7e,  // -OOOOOO-
    0x00,  // --------

    // ASCII: 50, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x7c,  // -OOOOO--
    0xc6,  // OO---OO-
    0x0e,  // ----OOO-
    0x3c,  // --OOOO--
    0x78,  // -OOOO---
    0xe0,  // OOO-----
    0xfe,  // OOOOOOO-
    0x00,  // --------

    // ASCII: 51, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x7e,  // -OOOOOO-
    0x0c,  // ----OO--
    0x18,  // ---OO---
    0x3c,  // --OOOO--
    0x06,  // -----OO-
    0xc6,  // OO---OO-
    0x7c,  // -OOOOO--
    0x00,  // --------

    // ASCII: 52, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x1c,  // ---OOO--
    0x3c,  // --OOOO--
    0x6c,  // -OO-OO--
    0xcc,  // OO--OO--
    0xfe,  // OOOOOOO-
    0x0c,  // ----OO--
    0x0c,  // ----OO--
    0x00,  // --------

    // ASCII: 53, char width: 8
    0x00,  // --------
    0x00,  // --------
    0xfc,  // OOOOOO--
    0xc0,  // OO------
    0xfc,  // OOOOOO--
    0x06,  // -----OO-
    0x06,  // -----OO-
    0xc6,  // OO---OO-
    0x7c,  // -OOOOO--
    0x00,  // --------

    // ASCII: 54, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x3c,  // --OOOO--
    0x60,  // -OO-----
    0xc0,  // OO------
    0xfc,  // OOOOOO--
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0x7c,  // -OOOOO--
    0x00,  // --------

    // ASCII: 55, char width: 8
    0x00,  // --------
    0x00,  // --------
    0xfe,  // OOOOOOO-
    0xc6,  // OO---OO-
    0x0c,  // ----OO--
    0x18,  // ---OO---
    0x30,  // --OO----
    0x30,  // --OO----
    0x30,  // --OO----
    0x00,  // --------

    // ASCII: 56, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x78,  // -OOOO---
    0xc4,  // OO---O--
    0xe4,  // OOO--O--
    0x78,  // -OOOO---
    0x9e,  // O--OOOO-
    0x86,  // O----OO-
    0x7c,  // -OOOOO--
    0x00,  // --------

    // ASCII: 57, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x7c,  // -OOOOO--
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0x7e,  // -OOOOOO-
    0x06,  // -----OO-
    0x0c,  // ----OO--
    0x78,  // -OOOO---
    0x00,  // --------

    // ASCII: 58, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x00,  // --------
    0x30,  // --OO----
    0x30,  // --OO----
    0x00,  // --------
    0x30,  // --OO----
    0x30,  // --OO----
    0x00,  // --------
    0x00,  // --------

    // ASCII: 59, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x00,  // --------
    0x30,  // --OO----
    0x30,  // --OO----
    0x00,  // --------
    0x30,  // --OO----
    0x30,  // --OO----
    0x60,  // -OO-----
    0x00,  // --------

    // ASCII: 60, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x0c,  // ----OO--
    0x18,  // ---OO---
    0x30,  // --OO----
    0x60,  // -OO-----
    0x30,  // --OO----
    0x18,  // ---OO---
    0x0c,  // ----OO--
    0x00,  // --------

    // ASCII: 61, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x00,  // --------
    0x00,  // --------
    0x7c,  // -OOOOO--
    0x00,  // --------
    0x7c,  // -OOOOO--
    0x00,  // --------
    0x00,  // --------
    0x00,  // --------

    // ASCII: 62, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x60,  // -OO-----
    0x30,  // --OO----
    0x18,  // ---OO---
    0x0c,  // ----OO--
    0x18,  // ---OO---
    0x30,  // --OO----
    0x60,  // -OO-----
    0x00,  // --------

    // ASCII: 63, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x7c,  // -OOOOO--
    0xfe,  // OOOOOOO-
    0xc6,  // OO---OO-
    0x0c,  // ----OO--
    0x38,  // --OOO---
    0x00,  // --------
    0x38,  // --OOO---
    0x00,  // --------

    // ASCII: 64, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x3c,  // --OOOO--
    0x66,  // -OO--OO-
    0xce,  // OO--OOO-
    0xce,  // OO--OOO-
    0xc0,  // OO------
    0x66,  // -OO--OO-
    0x3c,  // --OOOO--
    0x00,  // --------

    // ASCII: 65, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x38,  // --OOO---
    0x6c,  // -OO-OO--
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0xfe,  // OOOOOOO-
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0x00,  // --------

    // ASCII: 66, char width: 8
    0x00,  // --------
    0x00,  // --------
    0xfc,  // OOOOOO--
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0xfc,  // OOOOOO--
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0xfc,  // OOOOOO--
    0x00,  // --------

    // ASCII: 67, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x3c,  // --OOOO--
    0x66,  // -OO--OO-
    0xc0,  // OO------
    0xc0,  // OO------
    0xc0,  // OO------
    0x66,  // -OO--OO-
    0x3c,  // --OOOO--
    0x00,  // --------

    // ASCII: 68, char width: 8
    0x00,  // --------
    0x00,  // --------
    0xf8,  // OOOOO---
    0xcc,  // OO--OO--
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0xcc,  // OO--OO--
    0xf8,  // OOOOO---
    0x00,  // --------

    // ASCII: 69, char width: 8
    0x00,  // --------
    0x00,  // --------
    0xfe,  // OOOOOOO-
    0xc0,  // OO------
    0xc0,  // OO------
    0xfc,  // OOOOOO--
    0xc0,  // OO------
    0xc0,  // OO------
    0xfe,  // OOOOOOO-
    0x00,  // --------

    // ASCII: 70, char width: 8
    0x00,  // --------
    0x00,  // --------
    0xfe,  // OOOOOOO-
    0xc0,  // OO------
    0xc0,  // OO------
    0xfc,  // OOOOOO--
    0xc0,  // OO------
    0xc0,  // OO------
    0xc0,  // OO------
    0x00,  // --------

    // ASCII: 71, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x3e,  // --OOOOO-
    0x60,  // -OO-----
    0xc0,  // OO------
    0xce,  // OO--OOO-
    0xc6,  // OO---OO-
    0x66,  // -OO--OO-
    0x3e,  // --OOOOO-
    0x00,  // --------

    // ASCII: 72, char width: 8
    0x00,  // --------
    0x00,  // --------
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0xfe,  // OOOOOOO-
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0x00,  // --------

    // ASCII: 73, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x7e,  // -OOOOOO-
    0x18,  // ---OO---
    0x18,  // ---OO---
    0x18,  // ---OO---
    0x18,  // ---OO---
    0x18,  // ---OO---
    0x7e,  // -OOOOOO-
    0x00,  // --------

    // ASCII: 74, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x06,  // -----OO-
    0x06,  // -----OO-
    0x06,  // -----OO-
    0x06,  // -----OO-
    0x06,  // -----OO-
    0xc6,  // OO---OO-
    0x7c,  // -OOOOO--
    0x00,  // --------

    // ASCII: 75, char width: 8
    0x00,  // --------
    0x00,  // --------
    0xc6,  // OO---OO-
    0xcc,  // OO--OO--
    0xd8,  // OO-OO---
    0xf0,  // OOOO----
    0xf8,  // OOOOO---
    0xdc,  // OO-OOO--
    0xce,  // OO--OOO-
    0x00,  // --------

    // ASCII: 76, char width: 8
    0x00,  // --------
    0x00,  // --------
    0xc0,  // OO------
    0xc0,  // OO------
    0xc0,  // OO------
    0xc0,  // OO------
    0xc0,  // OO------
    0xc0,  // OO------
    0xfe,  // OOOOOOO-
    0x00,  // --------

    // ASCII: 77, char width: 8
    0x00,  // --------
    0x00,  // --------
    0xc6,  // OO---OO-
    0xee,  // OOO-OOO-
    0xfe,  // OOOOOOO-
    0xfe,  // OOOOOOO-
    0xd6,  // OO-O-OO-
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0x00,  // --------

    // ASCII: 78, char width: 8
    0x00,  // --------
    0x00,  // --------
    0xc6,  // OO---OO-
    0xe6,  // OOO--OO-
    0xf6,  // OOOO-OO-
    0xfe,  // OOOOOOO-
    0xde,  // OO-OOOO-
    0xce,  // OO--OOO-
    0xc6,  // OO---OO-
    0x00,  // --------

    // ASCII: 79, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x7c,  // -OOOOO--
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0x7c,  // -OOOOO--
    0x00,  // --------

    // ASCII: 80, char width: 8
    0x00,  // --------
    0x00,  // --------
    0xfc,  // OOOOOO--
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0xfc,  // OOOOOO--
    0xc0,  // OO------
    0xc0,  // OO------
    0x00,  // --------

    // ASCII: 81, char width: 9
    0x00,  // --------
    0x00,  // --------
    0x7c,  // -OOOOO--
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0xde,  // OO-OOOO-
    0xcc,  // OO--OO--
    0x7a,  // -OOOO-O-
    0x00,  // --------

    // ASCII: 82, char width: 8
    0x00,  // --------
    0x00,  // --------
    0xfc,  // OOOOOO--
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0xce,  // OO--OOO-
    0xf8,  // OOOOO---
    0xdc,  // OO-OOO--
    0xce,  // OO--OOO-
    0x00,  // --------

    // ASCII: 83, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x78,  // -OOOO---
    0xcc,  // OO--OO--
    0xc0,  // OO------
    0x7c,  // -OOOOO--
    0x06,  // -----OO-
    0xc6,  // OO---OO-
    0x7c,  // -OOOOO--
    0x00,  // --------

    // ASCII: 84, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x7e,  // -OOOOOO-
    0x18,  // ---OO---
    0x18,  // ---OO---
    0x18,  // ---OO---
    0x18,  // ---OO---
    0x18,  // ---OO---
    0x18,  // ---OO---
    0x00,  // --------

    // ASCII: 85, char width: 8
    0x00,  // --------
    0x00,  // --------
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0x7c,  // -OOOOO--
    0x00,  // --------

    // ASCII: 86, char width: 8
    0x00,  // --------
    0x00,  // --------
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0xee,  // OOO-OOO-
    0x7c,  // -OOOOO--
    0x38,  // --OOO---
    0x10,  // ---O----
    0x00,  // --------

    // ASCII: 87, char width: 8
    0x00,  // --------
    0x00,  // --------
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0xd6,  // OO-O-OO-
    0xfe,  // OOOOOOO-
    0xfe,  // OOOOOOO-
    0xee,  // OOO-OOO-
    0xc6,  // OO---OO-
    0x00,  // --------

    // ASCII: 88, char width: 8
    0x00,  // --------
    0x00,  // --------
    0xc6,  // OO---OO-
    0xee,  // OOO-OOO-
    0x7c,  // -OOOOO--
    0x38,  // --OOO---
    0x7c,  // -OOOOO--
    0xee,  // OOO-OOO-
    0xc6,  // OO---OO-
    0x00,  // --------

    // ASCII: 89, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x66,  // -OO--OO-
    0x66,  // -OO--OO-
    0x66,  // -OO--OO-
    0x3c,  // --OOOO--
    0x18,  // ---OO---
    0x18,  // ---OO---
    0x18,  // ---OO---
    0x00,  // --------

    // ASCII: 90, char width: 8
    0x00,  // --------
    0x00,  // --------
    0xfe,  // OOOOOOO-
    0x0e,  // ----OOO-
    0x1c,  // ---OOO--
    0x38,  // --OOO---
    0x70,  // -OOO----
    0xe0,  // OOO-----
    0xfe,  // OOOOOOO-
    0x00,  // --------

    // ASCII: 91, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x3c,  // --OOOO--
    0x30,  // --OO----
    0x30,  // --OO----
    0x30,  // --OO----
    0x30,  // --OO----
    0x30,  // --OO----
    0x3c,  // --OOOO--
    0x00,  // --------

    // ASCII: 92, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x80,  // O-------
    0x40,  // -O------
    0x20,  // --O-----
    0x10,  // ---O----
    0x08,  // ----O---
    0x04,  // -----O--
    0x02,  // ------O-
    0x00,  // --------

    // ASCII: 93, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x78,  // -OOOO---
    0x18,  // ---OO---
    0x18,  // ---OO---
    0x18,  // ---OO---
    0x18,  // ---OO---
    0x18,  // ---OO---
    0x78,  // -OOOO---
    0x00,  // --------

    // ASCII: 94, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x10,  // ---O----
    0x28,  // --O-O---
    0x44,  // -O---O--
    0x00,  // --------
    0x00,  // --------
    0x00,  // --------
    0x00,  // --------
    0x00,  // --------

    // ASCII: 95, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x00,  // --------
    0x00,  // --------
    0x00,  // --------
    0x00,  // --------
    0x00,  // --------
    0x00,  // --------
    0x00,  // --------
    0xfe,  // OOOOOOO-

    // ASCII: 96, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x10,  // ---O----
    0x08,  // ----O---
    0x04,  // -----O--
    0x00,  // --------
    0x00,  // --------
    0x00,  // --------
    0x00,  // --------
    0x00,  // --------

    // ASCII: 97, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x38,  // --OOO---
    0x6c,  // -OO-OO--
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0xfe,  // OOOOOOO-
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0x00,  // --------

    // ASCII: 98, char width: 8
    0x00,  // --------
    0x00,  // --------
    0xfc,  // OOOOOO--
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0xfc,  // OOOOOO--
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0xfc,  // OOOOOO--
    0x00,  // --------

    // ASCII: 99, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x3c,  // --OOOO--
    0x66,  // -OO--OO-
    0xc0,  // OO------
    0xc0,  // OO------
    0xc0,  // OO------
    0x66,  // -OO--OO-
    0x3c,  // --OOOO--
    0x00,  // --------

    // ASCII: 100, char width: 8
    0x00,  // --------
    0x00,  // --------
    0xf8,  // OOOOO---
    0xcc,  // OO--OO--
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0xcc,  // OO--OO--
    0xf8,  // OOOOO---
    0x00,  // --------

    // ASCII: 101, char width: 8
    0x00,  // --------
    0x00,  // --------
    0xfe,  // OOOOOOO-
    0xc0,  // OO------
    0xc0,  // OO------
    0xfc,  // OOOOOO--
    0xc0,  // OO------
    0xc0,  // OO------
    0xfe,  // OOOOOOO-
    0x00,  // --------

    // ASCII: 102, char width: 8
    0x00,  // --------
    0x00,  // --------
    0xfe,  // OOOOOOO-
    0xc0,  // OO------
    0xc0,  // OO------
    0xfc,  // OOOOOO--
    0xc0,  // OO------
    0xc0,  // OO------
    0xc0,  // OO------
    0x00,  // --------

    // ASCII: 103, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x3e,  // --OOOOO-
    0x60,  // -OO-----
    0xc0,  // OO------
    0xce,  // OO--OOO-
    0xc6,  // OO---OO-
    0x66,  // -OO--OO-
    0x3e,  // --OOOOO-
    0x00,  // --------

    // ASCII: 104, char width: 8
    0x00,  // --------
    0x00,  // --------
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0xfe,  // OOOOOOO-
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0x00,  // --------

    // ASCII: 105, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x7e,  // -OOOOOO-
    0x18,  // ---OO---
    0x18,  // ---OO---
    0x18,  // ---OO---
    0x18,  // ---OO---
    0x18,  // ---OO---
    0x7e,  // -OOOOOO-
    0x00,  // --------

    // ASCII: 106, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x06,  // -----OO-
    0x06,  // -----OO-
    0x06,  // -----OO-
    0x06,  // -----OO-
    0x06,  // -----OO-
    0xc6,  // OO---OO-
    0x7c,  // -OOOOO--
    0x00,  // --------

    // ASCII: 107, char width: 8
    0x00,  // --------
    0x00,  // --------
    0xc6,  // OO---OO-
    0xcc,  // OO--OO--
    0xd8,  // OO-OO---
    0xf0,  // OOOO----
    0xf8,  // OOOOO---
    0xdc,  // OO-OOO--
    0xce,  // OO--OOO-
    0x00,  // --------

    // ASCII: 108, char width: 8
    0x00,  // --------
    0x00,  // --------
    0xc0,  // OO------
    0xc0,  // OO------
    0xc0,  // OO------
    0xc0,  // OO------
    0xc0,  // OO------
    0xc0,  // OO------
    0xfe,  // OOOOOOO-
    0x00,  // --------

    // ASCII: 109, char width: 8
    0x00,  // --------
    0x00,  // --------
    0xc6,  // OO---OO-
    0xee,  // OOO-OOO-
    0xfe,  // OOOOOOO-
    0xfe,  // OOOOOOO-
    0xd6,  // OO-O-OO-
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0x00,  // --------

    // ASCII: 110, char width: 8
    0x00,  // --------
    0x00,  // --------
    0xc6,  // OO---OO-
    0xe6,  // OOO--OO-
    0xf6,  // OOOO-OO-
    0xfe,  // OOOOOOO-
    0xde,  // OO-OOOO-
    0xce,  // OO--OOO-
    0xc6,  // OO---OO-
    0x00,  // --------

    // ASCII: 111, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x7c,  // -OOOOO--
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0x7c,  // -OOOOO--
    0x00,  // --------

    // ASCII: 112, char width: 8
    0x00,  // --------
    0x00,  // --------
    0xfc,  // OOOOOO--
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0xfc,  // OOOOOO--
    0xc0,  // OO------
    0xc0,  // OO------
    0x00,  // --------

    // ASCII: 113, char width: 9
    0x00,  // --------
    0x00,  // --------
    0x7c,  // -OOOOO--
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0xde,  // OO-OOOO-
    0xcc,  // OO--OO--
    0x7a,  // -OOOO-O-
    0x00,  // --------

    // ASCII: 114, char width: 8
    0x00,  // --------
    0x00,  // --------
    0xfc,  // OOOOOO--
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0xce,  // OO--OOO-
    0xf8,  // OOOOO---
    0xdc,  // OO-OOO--
    0xce,  // OO--OOO-
    0x00,  // --------

    // ASCII: 115, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x78,  // -OOOO---
    0xcc,  // OO--OO--
    0xc0,  // OO------
    0x7c,  // -OOOOO--
    0x06,  // -----OO-
    0xc6,  // OO---OO-
    0x7c,  // -OOOOO--
    0x00,  // --------

    // ASCII: 116, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x7e,  // -OOOOOO-
    0x18,  // ---OO---
    0x18,  // ---OO---
    0x18,  // ---OO---
    0x18,  // ---OO---
    0x18,  // ---OO---
    0x18,  // ---OO---
    0x00,  // --------

    // ASCII: 117, char width: 8
    0x00,  // --------
    0x00,  // --------
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0x7c,  // -OOOOO--
    0x00,  // --------

    // ASCII: 118, char width: 8
    0x00,  // --------
    0x00,  // --------
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0xee,  // OOO-OOO-
    0x7c,  // -OOOOO--
    0x38,  // --OOO---
    0x10,  // ---O----
    0x00,  // --------

    // ASCII: 119, char width: 8
    0x00,  // --------
    0x00,  // --------
    0xc6,  // OO---OO-
    0xc6,  // OO---OO-
    0xd6,  // OO-O-OO-
    0xfe,  // OOOOOOO-
    0xfe,  // OOOOOOO-
    0xee,  // OOO-OOO-
    0xc6,  // OO---OO-
    0x00,  // --------

    // ASCII: 120, char width: 8
    0x00,  // --------
    0x00,  // --------
    0xc6,  // OO---OO-
    0xee,  // OOO-OOO-
    0x7c,  // -OOOOO--
    0x38,  // --OOO---
    0x7c,  // -OOOOO--
    0xee,  // OOO-OOO-
    0xc6,  // OO---OO-
    0x00,  // --------

    // ASCII: 121, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x66,  // -OO--OO-
    0x66,  // -OO--OO-
    0x66,  // -OO--OO-
    0x3c,  // --OOOO--
    0x18,  // ---OO---
    0x18,  // ---OO---
    0x18,  // ---OO---
    0x00,  // --------

    // ASCII: 122, char width: 8
    0x00,  // --------
    0x00,  // --------
    0xfe,  // OOOOOOO-
    0x0e,  // ----OOO-
    0x1c,  // ---OOO--
    0x38,  // --OOO---
    0x70,  // -OOO----
    0xe0,  // OOO-----
    0xfe,  // OOOOOOO-
    0x00,  // --------

    // ASCII: 123, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x3c,  // --OOOO--
    0x30,  // --OO----
    0x30,  // --OO----
    0x70,  // -OOO----
    0x30,  // --OO----
    0x30,  // --OO----
    0x3c,  // --OOOO--
    0x00,  // --------

    // ASCII: 124, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x30,  // --OO----
    0x30,  // --OO----
    0x30,  // --OO----
    0x30,  // --OO----
    0x30,  // --OO----
    0x30,  // --OO----
    0x30,  // --OO----
    0x00,  // --------

    // ASCII: 125, char width: 8
    0x00,  // --------
    0x00,  // --------
    0x78,  // -OOOO---
    0x18,  // ---OO---
    0x18,  // ---OO---
    0x1c,  // ---OOO--
    0x18,  // ---OO---
    0x18,  // ---OO---
    0x78,  // -OOOO---
    0x00,  // --------
};

static fontStyle_t __attribute__ ((unused)) FontStyle_Emulogic = 
{
    94, // Glyph count
    32, // First ascii code
    1, // Glyph width (bytes)
    10, // Glyph height (bytes)
    8, // Fixed width or 0 if variable
    (uint8_t*)0,
    Emulogic_Bitmaps
};

#endif /* FONTLIBRARY_H_ */